name: root
channels:
- conda-forge
- defaults
- brian-team
dependencies:
- python=2.7.*
- brian2
- jupyter_contrib_core
- jupyter_nbextensions_configurator
- cython
- decorator
- ipaddress
- ipykernel
- ipython
- ipython-notebook=4.0.4
- ipython-qtconsole
- ipython_genutils
- ipywidgets=7.0.*
- joblib==0.8.4
- jupyter_client=5.1.0
- jupyter_core=4.3.0
- matplotlib=1.5.1
- nbconvert
- nbformat
- notebook=5.0.*
- numpy
- pyparsing
- scipy
- sympy
- tornado
