#!/bin/bash

#source activate kernel
pip install jupyter_contrib_nbextensions==0.3.3
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable init_cell/main
jupyter nbextension enable hide_input_all/main
conda install -c conda-forge ipywidgets==7.0.0
jupyter nbextension enable --py widgetsnbextension

find . -name '*.ipynb' -exec jupyter trust {} \;

source activate kernel
# Fix matplotlib font cache
rm -rf /home/main/.matplolib
rm -rf /home/main/.cache/matplolib
rm -rf /home/main/.cache/fontconfig
python -c "import matplotlib.pyplot as plt"
